server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/test
    driver-class-name: com.mysql.jdbc.Driver
    name: root
    password: root

  profiles:
    active: dev

  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
#  mvc:
#    static-path-pattern: /image/**,classpath:/static